apiVersion: apps/v1

kind: Deployment

metadata:

  name: todoapp-deployment

  labels:

    app: todoapp

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todoapp

  template:

    metadata:

      labels:

        app: todoapp

    spec:

      containers:

      - name: todo-app

        image: public.ecr.aws/o0s3r5b6/todoapp:latest

        ports:

        - containerPort: 8000

